export * from "./endpoint/apiReg005";
export { default as apiReg005 } from "./endpoint/apiReg005";
export * from "./endpoint/apiReg006";
export { default as apiReg006 } from "./endpoint/apiReg006";
export * from "./endpoint/apiReg007";
export { default as apiReg007 } from "./endpoint/apiReg007";
export * from "./endpoint/apiReg008";
export { default as apiReg008 } from "./endpoint/apiReg008";
export * from "./endpoint/apiReg013";
export { default as apiReg013 } from "./endpoint/apiReg013";
export * from "./endpoint/apiReg019";
export { default as apiReg019 } from "./endpoint/apiReg019";
export * from "./endpoint/apiReg020";
export { default as apiReg020 } from "./endpoint/apiReg020";
export * from "./endpoint/apiReg026";
export { default as apiReg026 } from "./endpoint/apiReg026";
export * from "./endpoint/apiReg028";
export { default as apiReg028 } from "./endpoint/apiReg028";
